mybatis:
  postType-aliases-package: cn.edu.swpu.cins.event.analyse.platform.model.persistence
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true
    use-column-label: true
    map-underscore-to-camel-case: true

spring:
  datasource:
#    password: cinscinsb511
    password: 123
    username: root
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://182.150.37.58:3306/university_event_analyse?useUnicode=true&characterEncoding=utf8&useSSL=false
    url: jdbc:mysql://127.0.0.1/baidu_event?useUnicode=true&characterEncoding=utf8&useSSL=false
server:
  port: 4000


event:
  service:
    page-count: 5 #每页展示的事件个数
